using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Statecraft.Common.Enums
{
    public enum Territory
    {
        Ankara,
        Belgium,
        Berlin,
        Brest,
        Budapest,
        Bulgaria,
        Constantinople,
        Denmark,
        Edinburgh,
        Greece,
        Holland,
        Kiel,
        Liverpool,
        London,
        Marseilles,
        Moscow,
        Munich,
        Naples,
        Norway,
        Paris,
        Portugal,
        Rome,
        Rumania,
        SaintPetersburg,
        Serbia,
        Sevastopol,
        Smyrna,
        Spain,
        Sweden,
        Trieste,
        Tunis,
        Venice,
        Vienna,
        Warsaw,
        Clyde,
        Yorkshire,
        Wales,
        Picardy,
        Gascony,
        Burgundy,
        NorthAfrica,
        Ruhr,
        Prussia,
        Silesia,
        Piedmont,
        Tuscany,
        Apulia,
        Tyrolia,
        Galicia,
        Bohemia,
        Finland,
        Livonia,
        Ukraine,
        Albania,
        Armenia,
        Syria,
        NorthAtlanticOcean,
        MidAtlanticOcean,
        NorweigianSea,
        NorthSea,
        EnglishChannel,
        IrishSea,
        HeligolandBlight,
        Skagerrak,
        BalticSea,
        GulfofBothnia,
        BerentsSea,
        WesternMediterranean,
        GulfofLyonsn,
        TyrrhenianSea,
        IonianSea,
        AdriaticSea,
        AegeanSea,
        EasternMediterranean,
        BlackSea
    }
}
