#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Statecraft.App.Resource", IsApplication=true)]

namespace Statecraft.App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_chevron_left_black_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_chevron_right_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_done_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_forum_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_more_horiz_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int landUnit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int map = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int seaUnit = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int CreateGameButton = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int JoinGameButton = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int YourGamesText = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int ankaraUnit = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int berentsUnit = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int horizontalScrollView1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int map = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int menu_all_games = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int menu_back = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int menu_commit = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int menu_forward = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int menu_game_intent = 2131165198;
			
			// aapt resource value: 0x7f070009
			public const int menu_messages = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int menu_settings = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int stPetersUnit = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int toolbar = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Game = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int toolbar = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int top_menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int GameTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
